sudo: required
services:
  - docker

before_install:
  - docker build -t asalhani/docker-react -f Dockerfile.dev .

script:
  - docker run asalhani/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react02"
  env: "Dockerreact02-env"
  bucket_name: "elasticbeanstalk-us-east-1-799048763931"
  bucket_path: "docker-react02"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

